---
- hosts: capsules
  remote_user: root
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - role: ../common/roles/epel-not-present
    - role: ../common/roles/scalelab-generic-cleanup
      when: '"scalelab" in inventory_hostname'
    - role: ../common/roles/plain-network
      when: 'configure_plain_network == True'
    - role: ../common/roles/common
    - role: rhsm_helper
      vars:
        registration_options: "{{ capsule_registration_options }}"
    - role: repo_setup
      vars:
        additional_repos: "{{ capsule_additional_repos }}"
    - role: linux-system-roles.timesync
    - role: upgrade-restart
    - role: ../common/roles/remove-home-extend-root
      when: 'remove_home_partition|bool == True or extend_root_partition|bool == True'
    - role: linux-system-roles.firewall
      vars:
        firewall:
          - service: "RH-Satellite-6-capsule"
            state: enabled
    - role: ../common/roles/partition-new-storage
      vars:
        storage_pools: "{{ capsule_storage_pools }}"
      when:
        - capsule_storage_pools is defined and capsule_storage_pools|length > 0
    - role: capsule
    - role: capsule-location
    - role: ../common/roles/enlarge-arp-table
    - role: puppet-autosign
    - role: capsule-populate
...
