---
- hosts: capsules
  remote_user: root
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - ../common/roles/common
    - ../common/roles/epel-not-present
    - ../common/roles/rhsm-satellite
    - linux-system-roles.timesync
    - ../common/roles/remove-home-extend-root
    - capsule
    - capsule-location
    - ../common/roles/enlarge-arp-table
    ###- capsule-myrhev-partitioning
    - puppet-autosign
    - capsule-populate
