---
- hosts: container_hosts
  remote_user: root
  gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - role: client-scripts
    - role: repo_setup
      vars:
        additional_repos: "{{ containers_host_additional_repos }}"
  tasks:
    - name: "Install Ansible"
      package:
        name: ansible
        state: present

    - name: "Ansible should not check host keys"
      lineinfile:
        dest: /etc/ansible/ansible.cfg
        regexp: '^.*host_key_checking'
        line: 'host_key_checking = False'
        state: present
...
