---
- hosts: satellite6:capsules
  gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  vars:
    hgrg: "host-registration generate-command --organization-id {{ sat_orgid }} --activation-key {{ ak }} --jwt-expiration {{ jwt_expiration | default(720) | int }} --insecure true --force true"
  tasks:
    - name: "Check if running in a capsule"
      ansible.builtin.set_fact:
        hgrg: "{{ hgrg }} --smart-proxy {{ inventory_hostname }}"
      when: "'capsules' in group_names"

    - name: "Check if Insights client should be installed and configured (it won't be by default)"
      ansible.builtin.set_fact:
        hgrg: "{{ hgrg }} --setup-insights false"
      when: "hostvars[inventory_hostname].setup_insights is not defined or hostvars[inventory_hostname].setup_insights | bool == False"

    - name: "Check if MQTT REX mode is needed"
      ansible.builtin.set_fact:
        hgrg: "{{ hgrg }} --setup-remote-execution-pull true"
      when:
        - hostvars[inventory_hostname].rex_mode is defined and hostvars[inventory_hostname].rex_mode == 'mqtt'

    - name: "Check if some package should be installed"
      ansible.builtin.set_fact:
        hgrg: "{{ hgrg }} --packages {{ packages }}"
      when: "packages is defined and packages | length > 0"

    - name: "Generate the host registration command"
      ansible.builtin.command:
        hammer -u {{ sat_user}} -p {{ sat_pass }} {{ hgrg }}
      register: cmd
      delegate_to: "{{ groups['satellite6'] | first }}"

    - name: Copy the output of the the host registration command to the Apache pub directory
      ansible.builtin.copy:
        content: "{{ cmd.stdout }}"
        dest: /var/www/html/pub/host-registration.sh
      when: "cmd.rc == 0"
...
