---
- hosts: satellite6
  remote_user: root
  gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  tasks:
    - name: "Create OS"
      shell:
        hammer os create --architectures x86_64 --family Redhat --name "{{ containers_os.name }}" --major "{{ containers_os.major }}" --minor "{{ containers_os.minor }}"
    - name: "Create Hostgroup"
      shell:
        hammer hostgroup create --content-view "{{ Default_Organization }} View" --lifecycle-environment Library --name "{{ hostgroup_name }}" --query-organization "{{ Default_Organization }}" --subnet "{{ subnet_name }}" --operatingsystem "{{ containers_os.name }} {{ containers_os.major}}.{{containers_os.minor}}" --group-parameters-attributes "name=kt_activation_keys\,value=ActivationKey"
