---
- hosts: satellite6
  remote_user: root
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - role: ../common/roles/scalelab-nic-cleanup
      when: '"scalelab" in inventory_hostname'
    - ../common/roles/common
    - ../common/roles/epel-not-present
    - ../common/roles/rhsm
    - linux-system-roles.timesync
    ###- upgrade-restart
    ###- satellite-ec2-partitioning
    - ../common/roles/remove-home-extend-root
#     - role: workaround-local-sat-repo
#       when: workaround_local_sat_repo is defined and workaround_local_sat_repo
    - setup
    - enable-remote-exec-by-ip
    - ../common/roles/enlarge-arp-table
    - puppet-autosign
    - role: satellite-populate
      tags: satellite-populate
    - role: client-content
      tags: client-content
...
