---
- hosts: satellite6
  remote_user: root
  ###gather_facts: no
  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - role: ../common/roles/common
    - role: ../common/roles/epel-not-present
    - role: rhsm_helper
      vars:
        registration_options: "{{ satellite_registration_options }}"
    - role: linux-system-roles.timesync
    ###- role: upgrade-restart
    ###- role: satellite-ec2-partitioning
    - role: ../common/roles/remove-home-extend-root
    - role: repo_setup
      vars:
        additional_repos: "{{ satellite_additional_repos }}"
    - role: linux-system-roles.firewall
      vars:
        firewall:
          - service: "RH-Satellite-6"
            state: enabled
    - role: setup
    - role: enable-remote-exec-by-ip
    - role: ../common/roles/enlarge-arp-table
    - role: puppet-autosign
    - role: satellite-populate
      tags: satellite-populate
...
