---
roles:
  - name: linux-system-roles.timesync

  - name: linux-system-roles.firewall

  - name: linux-system-roles.network

  - name: linux-system-roles.storage

  - name: rhsm_helper
    src: https://github.com/jhutar/ansible-role-rhsm_helper.git
    version: origin/main

  - name: repo_setup
    src: https://github.com/jhutar/ansible-role-repo_setup.git
    version: origin/main

collections: []
...
