---
roles:
  - name: linux-system-roles.timesync

  - name: linux-system-roles.firewall

  - name: linux-system-roles.network

  # Workaround for https://github.com/linux-system-roles/storage/issues/258
  ###- name: linux-system-roles.storage
  - name: linux-system-roles.storage
    src: git+https://github.com/jhutar/storage.git
    version: origin/fix1

  - name: rhsm_helper
    src: git+https://github.com/jhutar/ansible-role-rhsm_helper.git
    version: origin/main

  - name: repo_setup
    src: git+https://github.com/jhutar/ansible-role-repo_setup.git
    version: origin/main

collections: []
...
