---
# RHEL8 requirements
- name: "Enable satellite:el8 module"
  command: dnf -y module enable satellite:el8
  when: "ansible_distribution_major_version|int == 8"

# Now, finally install required packages
- name: "Package satellite installed"
  yum:
    name: "satellite"
    state: present
    update_cache: yes
  retries: 3
  delay: 10
  register: yum_install_satellite_cmd
  until: yum_install_satellite_cmd is not failed
- name: "Show installation result"
  debug:
    var: yum_install_satellite_cmd
- name: "Fail if satellite package installation failed"
  assert:
    that:
      - not yum_install_satellite_cmd.failed

# Figure out installer options
- name: "Ensure sat_version is string to avoid hard to detect issues"
  assert:
    that: sat_version is string
    fail_msg: "Variable 'sat_version' have to be string to avoid issues like one when we had 6.10 version interpretted as 6.1 (trailing '0' removed as it was interpreted as number)"
- name: "Determine base installer options"
  set_fact:
    sat_installer_options: "--foreman-initial-admin-email {{ sat_email }} --foreman-initial-admin-username {{ sat_user }} --foreman-initial-admin-password {{ sat_pass }}"
- name: "Determine Installer command line"
  set_fact:
    satellite_installer_cmd_line: "satellite-installer --scenario satellite {{ sat_installer_options }} {{ sat_installer_aditional_ops | default() }}"
- name: "Configure Insights connection on Satellite <6.12"
  set_fact:
    satellite_installer_cmd_line: "{{ satellite_installer_cmd_line }} --enable-foreman-plugin-rh-cloud --foreman-proxy-plugin-remote-execution-ssh-install-key=true"
  when:
    - sat_version is version('6.12', '<')
    - hostvars[inventory_hostname].setup_insights is not defined or hostvars[inventory_hostname].setup_insights|bool == False
- name: "Configure Insights connection on Satellite >=6.12"
  set_fact:
    satellite_installer_cmd_line: "{{ satellite_installer_cmd_line }} --foreman-proxy-plugin-remote-execution-script-install-key=true"
  when:
    - sat_version is version('6.12', '>=')
    - hostvars[inventory_hostname].setup_insights is not defined or hostvars[inventory_hostname].setup_insights|bool == False
- name: "Configure MQTT transport for remote execution on Satellite >=6.12"
  set_fact:
    satellite_installer_cmd_line: "{{ satellite_installer_cmd_line }} --foreman-proxy-plugin-remote-execution-script-mode=pull-mqtt"
  when:
    - sat_version is version('6.12', '>=')
    - hostvars[inventory_hostname].rex_mode is defined and hostvars[inventory_hostname].rex_mode == 'mqtt'

- name: "Show Installer command line"
  debug:
    msg: "{{ satellite_installer_cmd_line }}"

# Run the installer
- name: "Run Satellite configuration"
  shell: "{{ satellite_installer_cmd_line }}"
  environment:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    TZ: "UTC"
  register: satellite_installer_cmd

- name: "Show Satellite configuration output"
  ansible.builtin.debug:
    var: satellite_installer_cmd.stdout_lines

- name: "Print installer run duration"
  debug:
    msg: "SatelliteInstallerScenarioSatellite {{ satellite_installer_cmd.start }} to {{ satellite_installer_cmd.end }}"

- name: "Workaround for: Bug 2132774 - On its default configuration mosquitto cannot accept more than 1014 clients"
  ansible.builtin.copy:
    dest: /etc/systemd/system/mosquitto.service.d/limits.conf
    content: |
      [Service]
      LimitNOFILE=10000
  when:
    - sat_version is version('6.12', '>=')
    - hostvars[inventory_hostname].rex_mode is defined and hostvars[inventory_hostname].rex_mode == 'mqtt'

- name: Restart mosquitto service unit
  ansible.builtin.systemd:
    name: mosquitto
    daemon_reload: yes
    state: restarted
  when:
    - sat_version is version('6.12', '>=')
    - hostvars[inventory_hostname].rex_mode is defined and hostvars[inventory_hostname].rex_mode == 'mqtt'

- name: "Install the katello-client-bootstrap package"
  yum:
    name: katello-client-bootstrap
    state: present
...
