---
# RHEL8 requirements
- name: "Enable satellite:el8 module"
  command: dnf -y module enable satellite:el8
  when: "ansible_distribution_major_version|int == 8"

# Now, finally install required packages
- name: "Package satellite installed"
  yum:
    name: "satellite"
    state: present
    update_cache: yes
  retries: 3
  delay: 10
  register: yum_install_satellite_cmd
  until: yum_install_satellite_cmd is not failed
- name: "Show installation result"
  debug:
    var: yum_install_satellite_cmd
- name: "Fail if satellite package installation failed"
  assert:
    that:
      - not yum_install_satellite_cmd.failed

# Figure out installer options
- name: "Ensure sat_version is string to avoid hard to detect issues"
  assert:
    that: sat_version is string
    fail_msg: "Variable 'sat_version' have to be string to avoid issues like one when we had 6.10 version interpretted as 6.1 (trailing '0' removed as it was interpreted as number)"
- name: "Determine installer options for <=6.5"
  set_fact:
    sat_installer_options: "--foreman-admin-email {{ sat_email }} --foreman-admin-username {{ sat_user }} --foreman-admin-password {{ sat_pass }}"
  when: "sat_version is version('6.5', '<=')"
- name: "Determine installer options for >=6.6"
  set_fact:
    sat_installer_options: "--foreman-initial-admin-email {{ sat_email }} --foreman-initial-admin-username {{ sat_user }} --foreman-initial-admin-password {{ sat_pass }}"
  when: "sat_version is version('6.6', '>=')"

# Run the installer
- name: "Satellite configured"
  shell: |
    satellite-installer --scenario satellite {{ sat_installer_options }} {{ sat_installer_aditional_ops | default() }}
  environment:
    LANG: "en_US.UTF-8"
    LC_ALL: "en_US.UTF-8"
    TZ: "UTC"
  register: satellite_installer_cmd
- name: "Print installer run duration"
  debug:
    msg: "SatelliteInstallerScenarioSatellite {{ satellite_installer_cmd.start }} to {{ satellite_installer_cmd.end }}"

- name: "Install the katello-client-bootstrap package"
  yum:
    name: katello-client-bootstrap
    state: present
...
