---
- hosts: katello
  remote_user: root

  vars_files:
    - ../../conf/satperf.yaml
    - ../../conf/satperf.local.yaml
  roles:
    - ../common/roles/add-epel
    - ../common/roles/rhsm
    - linux-system-roles.timesync
    - ../common/roles/remove-home-extend-root
    - add_rhsm_repos
    - add_katello_repos
    - configure_firewall
    - add_host_to_hostfile
    - setup
