---
# Check variables
- name: "Make sure only one Satellite is specified"
  assert:
    that: "groups['satellite6']|length == 1"
    msg: "Satellite not specified or too many of them specified"
  when: "'satellite6' in groups and ( ignore_satellite is not defined or ignore_satellite != 'true' )"

# Make sure we have key deployed
- name: "Deploy key"
  authorized_key:
    user: root
    key: "{{ lookup('file', '../../../../../'+satperf_private_key+'.pub') }}"
    manage_dir: yes

# Cleanup ScaleLab systems
- name: "Cleanup ScaleLab systems"
  ansible.builtin.import_role:
    name: ../common/roles/scalelab-generic-cleanup
  when: '"scalelab" in inventory_hostname'

# Check default in /etc/hosts file
- name: "We need localhost (IPv4) in hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1\s+localhost localhost\.localdomain localhost4 localhost4\.localdomain4$'
    line: "127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4"
    state: present

- name: "We might need localhost (IPv6) in hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: '^::1\s+localhost localhost\.localdomain localhost6 localhost6\.localdomain6$'
    line: "::1   localhost localhost.localdomain localhost6 localhost6.localdomain6"
    state: present

# Make sure we have private IPs in /etc/hosts
# Taken from https://gist.github.com/rothgar/8793800
- name: "Build hosts file"
  lineinfile:
    dest: /etc/hosts
    regexp: ".*{{ item }}$"
    line: "{{ hostvars[item].private_ip }} {{ item }}"
    state: present
  when: "hostvars[item].private_ip is defined"
  with_items: "{{ groups['satellite6'] + groups['capsules'] }}"

- name: "File /etc/hosts have correct SELinux context (had issues before)"
  command:
    restorecon -vR /etc/hosts

# Check SELinux
- name: "SELinux is in Enforcing with Tragetted policy"
  selinux:
    policy: targeted
    state: enforcing

# Make sure hostname is set
- name: "Set hostname"
  hostname:
    name: "{{ inventory_hostname }}"

# Sanity check our networking setup
- name: "We can ping 127.0.0.1"
  wait_for:
    host: 127.0.0.1
    port: 22
    timeout: 3

- name: "We can ping localhost"
  wait_for:
    host: localhost
    port: 22
    timeout: 3

- name: "We can ping redhat.com"
  wait_for:
    host: redhat.com
    port: 443
    timeout: 10

- name: "We can ping Satellite"
  wait_for:
    host: "{{ groups['satellite6']|first }}"
    port: 22
    timeout: 50
  when: "ignore_satellite is not defined or ignore_satellite != 'true'"

- name: "We can ping Satellite via special network"
  wait_for:
    host: "{{ hostvars[groups['satellite6']|first].private_ip }}"
    port: 22
    timeout: 10
  when: "hostvars[groups['satellite6']|first].private_ip is defined and ( ignore_satellite is not defined or ignore_satellite != 'true' )"

- name: "We can ping NTP server"
  command:
    ping -c 3 "{{ ntp_server }}"

# Sanity check yum config
- name: "Command yum repolist returns"
  command: yum repolist
...
