---
- name: "Distribute clients.yaml"
  copy:
    src: "files/clients.yaml"
    dest: "/root/clients.yaml"
    force: yes

- name: "Install Ansible"
  package:
    name: ansible
    state: present

- name: "Ansible should not check host keys"
  lineinfile:
    dest: /etc/ansible/ansible.cfg
    regexp: '^.*host_key_checking'
    line: 'host_key_checking = False'
    state: present

- name: "Distribute private key"
  copy:
    src: "../../{{ client_private_key }}"
    dest: /root/id_rsa_key
    mode: "u=rw,g=,o="
    force: yes
...
