---
  # Add '*' autosign entry to Puppet CA of integrated capsule
  - name: "If file exists, it is enabled"
    ansible.builtin.stat:
      path: /etc/puppetlabs/puppet/autosign.conf
    register: stat_result

  - name: "Add '*' autosign entry"
    ansible.builtin.lineinfile:
      path: "/etc/puppetlabs/puppet/autosign.conf"
      line: "*"
    when:
      - stat_result.stat.exists
...
