---
- setup:
    gather_subset:
      - '!all'
      - hardware

# Set up required storage
- name: "Enable rhel-7-server-optional-rpms repo (to satisfy linux-system-roles.storage role dependencies)"
  community.general.rhsm_repository:
    name: "rhel-{{ ansible_distribution_major_version }}-server-optional-rpms"
  when: ansible_distribution_major_version|int == 7

- name: "Set up storage requirements"
  include_role:
    name: linux-system-roles.storage

- name: "Remove the packages required by the linux-system-roles.storage role in RHEL 7"
  yum:
    name: "{{ blivet_package_list }}"
    state: absent
    autoremove: yes
  vars:
    blivet_package_list:
      - python-enum34
      - python-blivet3
      - libblockdev-crypto
      - libblockdev-dm
      - libblockdev-lvm
      - libblockdev-mdraid
      - libblockdev-swap
  when: ansible_distribution_major_version|int == 7

- name: "Remove the packages required by the linux-system-roles.storage role in RHEL 8"
  yum:
    name: "{{ blivet_package_list }}"
    state: absent
    autoremove: yes
  vars:
    blivet_package_list:
      - python3-blivet
      - libblockdev-crypto
      - libblockdev-dm
      - libblockdev-lvm
      - libblockdev-mdraid
      - libblockdev-swap
      - vdo
      - kmod-kvdo
  when: ansible_distribution_major_version|int == 8

- name: "Disable rhel-7-server-optional-rpms repo (now that it's not needed)"
  community.general.rhsm_repository:
    name: "rhel-7-server-optional-rpms"
    state: disabled
  when: ansible_distribution_major_version|int == 7
